import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { readFile } from 'node:fs/promises';
import { sampleBilling, applySampleBilling } from '../examples/billing-demo.js';
import { validateBilling, invoiceText, formatBillingAmount } from '../src/js/billing.js';

test('billing snapshots validate exact money, quotas and invoice totals without losing caller data', async () => {
  const original = sampleBilling(), copy = validateBilling(original); copy.usage.projects = 99; expect(original.usage.projects).toBe(6);
  const bad = [data=>data.plans[0].monthly=1.2, data=>data.fractionDigits=4, data=>data.currency=['USD'], data=>data.period.end='2026-02-30', data=>data.usage.projects=-1, data=>data.invoices[0].total++, data=>data.invoices[0].paid=0, data=>data.invoices[2].paid=1, data=>data.invoices[0].items[0].quantity=1e12, data=>data.plans.push(data.plans[0]), data=>data.invoices.push(data.invoices[0])];
  for (const mutate of bad) { const data=sampleBilling(); mutate(data); expect(()=>validateBilling(data)).toThrow(); }
  expect(invoiceText(original,'studio-sep',{sample:true})).toContain('Total: $20.90\nPaid: $20.90\nOutstanding: $0.00');
  expect(invoiceText(original,'studio-oct')).toContain('Outstanding: $14.00'); expect(invoiceText(original,'studio-aug')).toContain('Outstanding: $0.00');
  expect(formatBillingAmount({...original,currency:'JPY',fractionDigits:0},1900)).toBe('¥1,900'); expect(formatBillingAmount({...original,currency:'KWD',fractionDigits:3},1900)).toBe('KWD 1.900');
  expect(applySampleBilling(original,{type:'plan',planId:'studio',interval:'yearly'}).period.end).toBe('2027-10-01'); const january=sampleBilling();january.period={start:'2026-01-31',end:'2026-02-28'};expect(applySampleBilling(january,{type:'plan',planId:'studio',interval:'monthly'}).period.end).toBe('2026-02-28');const leap=sampleBilling();leap.period={start:'2028-02-29',end:'2028-03-29'};expect(applySampleBilling(leap,{type:'plan',planId:'studio',interval:'yearly'}).period.end).toBe('2029-02-28');
});

test('native subscription review commits once, respects cancellation and resets to confirmed state', async ({page}) => {
  await page.goto('/examples/billing.html'); await page.evaluate(()=>window.billingEvents=[]); await page.evaluate(()=>document.querySelector('#main').addEventListener('rf:billing-change',event=>window.billingEvents.push(event.detail)));
  await page.getByRole('combobox',{name:'Requested plan',exact:true}).selectOption('organization'); await page.getByRole('radio',{name:'Yearly',exact:true}).check(); await expect(page.locator('[data-rf-plan-price="organization"]')).toHaveText('$470.40 / year');
  await page.getByRole('button',{name:'Review plan change',exact:true}).click(); const dialog=page.getByRole('dialog',{name:'Review subscription change',exact:true}); await expect(dialog).toContainText('Organization, $470.40 per year'); await page.keyboard.press('Escape'); await expect(page.locator('[data-rf-subscription-current]')).toHaveText('Studio · $19.00 / month');
  await page.getByRole('button',{name:'Review plan change',exact:true}).click(); await dialog.getByRole('button',{name:'Apply sample change',exact:true}).click(); await expect(dialog).not.toBeVisible(); await expect(page.locator('[data-rf-subscription-current]')).toHaveText('Organization · $470.40 / year'); await expect(page.locator('[data-rf-usage="projects"]')).toContainText('6 of unlimited');
  await expect(page.locator('[data-rf-billing-period]')).toContainText('2027-10-01'); await page.getByRole('button',{name:'Schedule cancellation',exact:true}).click(); await expect(dialog).toContainText('2027-10-01'); await dialog.getByRole('button',{name:'Apply sample change',exact:true}).click(); await expect(page.locator('[data-rf-subscription-state]')).toContainText('Cancellation scheduled');
  await page.getByRole('button',{name:'Keep subscription',exact:true}).click(); await dialog.getByRole('button',{name:'Apply sample change',exact:true}).click(); await expect(page.locator('[data-rf-subscription-state]')).toHaveText('No cancellation scheduled.');
  await page.getByRole('combobox',{name:'Requested plan',exact:true}).selectOption('personal'); await page.getByRole('button',{name:'Reset selection',exact:true}).click(); await expect(page.getByRole('combobox',{name:'Requested plan',exact:true})).toHaveValue('organization'); await expect(page.getByRole('radio',{name:'Yearly',exact:true})).toBeChecked();
  expect((await page.evaluate(()=>window.billingEvents)).map(event=>event.operation.type)).toEqual(['plan','cancel','resume']); await expect(page.locator('[data-rf-invoice-rows] tr')).toHaveCount(3);
  await page.getByRole('combobox',{name:'Requested plan',exact:true}).selectOption('personal'); await page.getByRole('radio',{name:'Monthly',exact:true}).check(); await page.evaluate(()=>document.querySelector('[data-rf-plan-form]').addEventListener('reset',event=>event.preventDefault(),{once:true})); await page.getByRole('button',{name:'Reset selection',exact:true}).click(); await expect(page.getByRole('combobox',{name:'Requested plan',exact:true})).toHaveValue('personal'); await expect(page.getByRole('radio',{name:'Monthly',exact:true})).toBeChecked();
});

test('invoice filters, native disclosures and downloads retain exact safe record text', async ({page}) => {
  await page.goto('/docs/index.html#component/invoice-history'); await page.getByRole('combobox',{name:'Invoice status',exact:true}).selectOption('open'); await expect(page.locator('[data-rf-invoice-row]:visible')).toHaveCount(1); await page.getByText('STUDIO-2026-10',{exact:true}).click(); await expect(page.locator('[data-rf-invoice-row="studio-oct"] pre')).toContainText('Outstanding: $14.00');
  const downloadPromise=page.waitForEvent('download'); await page.getByRole('link',{name:'Download invoice STUDIO-2026-10 as text',exact:true}).click(); const download=await downloadPromise; expect(await readFile(await download.path(),'utf8')).toBe(invoiceText(sampleBilling(),'studio-oct',{sample:true}));
  await page.getByLabel('Search invoices',{exact:true}).fill('no-invoice'); await expect(page.locator('[data-rf-invoice-empty]')).toBeVisible(); await page.getByLabel('Search invoices',{exact:true}).fill(''); await page.getByRole('combobox',{name:'Invoice status',exact:true}).selectOption(''); await page.getByText('STUDIO-2026-08',{exact:true}).click(); await expect(page.locator('[data-rf-invoice-row="studio-aug"] pre')).toContainText('Outstanding: $0.00');
  await page.evaluate(async()=>{const{createBillingManager}=await import('/src/js/billing.js');const{sampleBilling}=await import('/examples/billing-demo.js');const root=document.querySelector('[data-rf-billing-demo]');const manager=createBillingManager(root,{snapshot:sampleBilling()});const data=manager.getSnapshot();data.invoices[0].items[0].description='<img src=x onerror=alert(1)>';data.revision++;manager.update(data);}); await page.getByText('STUDIO-2026-09',{exact:true}).click(); await expect(page.locator('[data-rf-invoice-row="studio-sep"] pre')).toContainText('<img src=x onerror=alert(1)>'); await expect(page.locator('[data-rf-invoice-rows] img')).toHaveCount(0);
});

test('usage covers exact near, over, empty and unlimited quotas while preserving plan drafts', async ({page}) => {
  await page.goto('/examples/billing.html'); await page.getByRole('combobox',{name:'Requested plan',exact:true}).selectOption('organization'); await page.getByRole('radio',{name:'Yearly',exact:true}).check(); await page.getByRole('combobox',{name:'Try sample usage',exact:true}).selectOption('near'); await expect(page.locator('[data-rf-usage="projects"]')).toContainText('27 of 30 projects'); await expect(page.locator('[data-rf-usage="projects"]')).toContainText('Close to the limit'); await expect(page.getByRole('combobox',{name:'Requested plan',exact:true})).toHaveValue('organization'); await expect(page.getByRole('radio',{name:'Yearly',exact:true})).toBeChecked();
  await page.getByRole('combobox',{name:'Try sample usage',exact:true}).selectOption('over'); await expect(page.locator('[data-rf-usage="projects"]')).toContainText('31 of 30 projects'); await expect(page.locator('[data-rf-usage="projects"]')).toContainText('Over limit by 1.'); expect(await page.locator('[data-rf-usage="projects"] meter').evaluate(meter=>meter.value)).toBe(30);
  await page.getByRole('combobox',{name:'Try sample usage',exact:true}).selectOption('empty'); await expect(page.locator('[data-rf-usage="projects"]')).toContainText('0 of 30 projects');
  await page.getByRole('button',{name:'Review plan change',exact:true}).click(); await page.getByRole('button',{name:'Apply sample change',exact:true}).click(); await expect(page.locator('[data-rf-usage="projects"]')).toContainText('unlimited'); await expect(page.locator('[data-rf-usage="projects"] meter')).toHaveCount(0);
  await page.evaluate(async()=>{const{createBillingManager}=await import('/src/js/billing.js');const{sampleBilling}=await import('/examples/billing-demo.js');const manager=createBillingManager(document.querySelector('#main'),{snapshot:sampleBilling()});const data=manager.getSnapshot();data.plans.find(plan=>plan.id===data.subscription.planId).limits.seats=0;data.usage.seats=0;data.revision++;manager.update(data);}); await expect(page.locator('[data-rf-usage="seats"]')).toContainText('0 of 0 seats'); await expect(page.locator('[data-rf-usage="seats"]')).toContainText('At limit.');
});

test('failed, stale and timed-out confirmations retain state and require safe refresh; teardown ignores late results', async ({page}) => {
  test.setTimeout(45000); await page.goto('/examples/billing.html');
  await page.evaluate(async()=>{const{createBillingManager}=await import('/src/js/billing.js');const{sampleBilling,applySampleBilling}=await import('/examples/billing-demo.js');const root=document.querySelector('#main');createBillingManager(root,{snapshot:sampleBilling()}).destroy();window.billingMode='failed';window.billingCalls=0;window.billingAborted=false;window.billingManager=createBillingManager(root,{snapshot:sampleBilling(),sample:true,change:async(op,{signal})=>{window.billingCalls++;if(window.billingMode==='failed')throw Error('Save unavailable');if(window.billingMode==='stale')return sampleBilling();if(window.billingMode==='late')return new Promise(resolve=>window.resolveBilling=()=>resolve(applySampleBilling(sampleBilling(),op)));signal.addEventListener('abort',()=>window.billingAborted=true);return new Promise(()=>{});},load:async()=>sampleBilling()});});
  const review=async()=>{await page.getByRole('combobox',{name:'Requested plan',exact:true}).selectOption('organization');await page.getByRole('button',{name:'Review plan change',exact:true}).click();await page.getByRole('button',{name:'Apply sample change',exact:true}).click();};
  await review(); const dialog=page.getByRole('dialog',{name:'Review subscription change',exact:true}); await expect(dialog.getByRole('alert')).toContainText('Save unavailable'); await expect(dialog.getByRole('button',{name:'Apply sample change',exact:true})).toBeDisabled(); await page.keyboard.press('Escape'); await expect(page.getByRole('combobox',{name:'Requested plan',exact:true})).toBeDisabled(); await expect(page.locator('[data-rf-subscription-current]')).toHaveText('Studio · $19.00 / month');
  await page.locator('[data-rf-billing-refresh]').first().click(); await expect(page.getByRole('combobox',{name:'Requested plan',exact:true})).toBeEnabled(); await page.evaluate(()=>window.billingMode='stale'); await review(); await expect(dialog.getByRole('alert')).toContainText('newer snapshot'); await page.keyboard.press('Escape'); await page.locator('[data-rf-billing-refresh]').first().click();
  await page.evaluate(()=>window.billingMode='timeout'); await review(); await expect(dialog.getByRole('alert')).toContainText('timed out',{timeout:11000}); expect(await page.evaluate(()=>window.billingAborted)).toBe(true); await page.keyboard.press('Escape'); await page.locator('[data-rf-billing-refresh]').first().click();
  await page.evaluate(()=>window.billingMode='late'); await review(); await page.evaluate(()=>window.billingManager.destroy()); await expect(dialog).not.toBeVisible(); await page.evaluate(()=>window.resolveBilling()); await expect(page.locator('[data-rf-subscription-current]')).toHaveText('Studio · $19.00 / month'); expect(await page.evaluate(()=>window.billingManager.update(window.billingManager.getSnapshot()))).toBe(false); expect(await page.evaluate(()=>window.billingCalls)).toBe(4);
  await page.evaluate(async()=>{const{createBillingManager}=await import('/src/js/billing.js');const root=document.querySelector('#main');window.billingManager=createBillingManager(root,{snapshot:window.billingManager.getSnapshot()});const data=window.billingManager.getSnapshot();data.invoices[0].total++;try{window.billingManager.update(data);}catch{}const other=window.billingManager.getSnapshot();other.id='another-workspace';try{window.billingManager.update(other);}catch{}}); await expect(page.getByRole('combobox',{name:'Requested plan',exact:true})).toBeDisabled(); await expect(page.locator('[data-rf-subscription-current]')).toHaveText('Studio · $19.00 / month'); await expect(page.getByRole('combobox',{name:'Invoice status',exact:true})).toBeEnabled();
});

test('dashboard reuses billing components with actual project/member/file usage and workspace-isolated plans', async ({page}) => {
  await page.goto('/examples/dashboard.html#billing'); const billing=page.locator('#billing'); await expect(billing.locator('[data-rf-usage="projects"]')).toContainText('6 of 30 projects'); await expect(billing.locator('[data-rf-usage="seats"]')).toContainText('3 of 5 seats'); await expect(billing.locator('[data-rf-usage-preview]')).toBeHidden();
  const files=page.locator('[data-rf-file-browser]'), originalBytes=await files.evaluate(async element=>(await import('/src/js/file-browser.js')).createFileBrowser(element).getEntries().filter(entry=>entry.kind==='file'&&!entry.trashed).reduce((sum,entry)=>sum+entry.file.size,0)); await expect(billing.locator('[data-rf-usage="storageBytes"]')).toContainText(`${originalBytes.toLocaleString('en-US')} of 50,000,000 bytes`);
  await files.getByLabel('Project files').setInputFiles({name:'Quota.txt',mimeType:'text/plain',buffer:Buffer.from('123456789')}); await expect(billing.locator('[data-rf-usage="storageBytes"]')).toContainText(`${(originalBytes+9).toLocaleString('en-US')} of 50,000,000 bytes`); await files.getByRole('button',{name:'Trash item',exact:true}).click(); await files.getByRole('dialog').getByRole('button',{name:'Move to Trash',exact:true}).click(); await expect(billing.locator('[data-rf-usage="storageBytes"]')).toContainText(`${originalBytes.toLocaleString('en-US')} of 50,000,000 bytes`); await files.getByRole('button',{name:'Restore trash',exact:true}).click(); await expect(billing.locator('[data-rf-usage="storageBytes"]')).toContainText(`${(originalBytes+9).toLocaleString('en-US')} of 50,000,000 bytes`);
  await page.getByRole('button',{name:'New project +',exact:true}).click(); const create=page.getByRole('dialog',{name:'Make room for a new idea.',exact:true}); await create.getByRole('textbox',{name:'Project name',exact:true}).fill('A measured idea'); await create.getByRole('button',{name:'Create project',exact:true}).click(); await expect(billing.locator('[data-rf-usage="projects"]')).toContainText('7 of 30 projects');
  await page.getByRole('button',{name:'Remove Alex Morgan',exact:true}).click(); await page.getByRole('dialog',{name:'Confirm access change',exact:true}).getByRole('button',{name:'Confirm change',exact:true}).click(); await expect(billing.locator('[data-rf-usage="seats"]')).toContainText('2 of 5 seats');
  await billing.getByRole('combobox',{name:'Requested plan',exact:true}).selectOption('organization'); await billing.getByRole('button',{name:'Review plan change',exact:true}).click(); await page.getByRole('button',{name:'Apply sample change',exact:true}).click(); await expect(billing.locator('[data-rf-subscription-current]')).toHaveText('Organization · $49.00 / month');
  await page.getByRole('button',{name:'Switch workspace: Studio',exact:true}).click(); await page.getByRole('menuitem',{name:'Personal workspace',exact:true}).click(); await expect(billing.locator('[data-rf-subscription-current]')).toHaveText('Personal · $0.00 / month'); await expect(billing.locator('[data-rf-invoice-empty]')).toBeVisible(); await expect(billing.locator('[data-rf-usage="projects"]')).toContainText('2 of 3 projects');
  await page.getByRole('button',{name:'Account menu for Robin Francis',exact:true}).click(); await page.getByRole('menuitem',{name:'Billing & usage',exact:true}).click(); await expect(page).toHaveURL(/workspace=personal#billing$/); await expect(page.locator('.rf-breadcrumb [aria-current="page"]')).toHaveText('Billing & usage');
  await page.getByRole('button',{name:'Switch workspace: Personal',exact:true}).click(); await page.getByRole('menuitem',{name:'Studio workspace',exact:true}).click(); await expect(billing.locator('[data-rf-subscription-current]')).toHaveText('Organization · $49.00 / month'); await page.reload(); await expect(billing.locator('[data-rf-subscription-current]')).toHaveText('Studio · $19.00 / month');
  await page.goto('/docs/index.html#component/billing-switch'); await page.getByRole('link',{name:'Choose Personal',exact:true}).click(); await expect(page).toHaveURL(/workspace=personal#billing$/); await expect(page.locator('#billing [data-rf-subscription-current]')).toHaveText('Personal · $0.00 / month');
});

test('billing views fit narrow themes, pass axe and retain native invoice downloads without scripts', async ({page,browser}) => {
  test.setTimeout(90000); // Six complete theme/viewport scans plus the native scripts-off download.
  // Firefox keeps transitions inside closed native details pending; wait for painted controls.
  for(const width of [320,390,1440]) { await page.setViewportSize({width,height:900}); await page.goto('/examples/billing.html'); for(const theme of ['light','dark']) {await page.evaluate(theme=>document.documentElement.dataset.rfTheme=theme,theme);await page.getByText('STUDIO-2026-09',{exact:true}).click();await page.waitForFunction(()=>document.getAnimations().filter(animation=>'transitionProperty' in animation && animation.effect.target.checkVisibility({contentVisibilityAuto:true})).every(animation=>animation.playState!=='running' && !animation.pending));expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);await page.getByText('STUDIO-2026-09',{exact:true}).click();} }
  await page.emulateMedia({reducedMotion:'reduce'}); expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
  const context=await browser.newContext({javaScriptEnabled:false}), native=await context.newPage(); await native.goto('/examples/billing.html'); await expect(native.getByRole('heading',{name:'Subscription management',exact:true})).toBeVisible(); await expect(native.getByRole('button',{name:'Review plan change',exact:true})).toBeDisabled(); await native.getByText('STUDIO-2026-09',{exact:true}).click(); const pending=native.waitForEvent('download'); await native.getByRole('link',{name:'Download sample invoice text',exact:true}).click(); const download=await pending; expect(await readFile(await download.path(),'utf8')).toBe(invoiceText(sampleBilling(),'studio-sep',{sample:true})); await context.close();
});
