import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { applyTeamChange, acceptTeamInvitation, validateTeam } from '../src/js/team-management.js';

const route = '/docs/index.html#component/team-management', root = page => page.locator('[data-rf-team-manager]');
const confirm = async page => page.getByRole('dialog', { name: 'Confirm access change' }).getByRole('button', { name: 'Confirm change', exact: true }).click();
const invite = async (page, email, role = 'viewer') => { await page.getByLabel('Invitation email', { exact: true }).fill(email); await page.getByRole('combobox', { name: 'Invitation role', exact: true }).selectOption(role); await page.getByRole('button', { name: 'Create invitation', exact: true }).click(); };
const auth = session => ({ Authorization: `Bearer ${session.accessToken}` });
const teamUrl = session => `/api/sample-teams/${session.team.id}`;
const create = async request => (await (await request.post('/api/sample-teams', { data: {} })).json());
const change = async (request, session, operation, revision) => request.post(teamUrl(session), { headers: auth(session), data: { revision: revision ?? (await (await request.get(teamUrl(session), { headers: auth(session) })).json()).team.revision, operation } });
const tokenQuery = link => `?token=${new URL(link).searchParams.get('token')}`;
const join = async (request, session, email, role) => { const result = await (await change(request, session, { type: 'invite', email, role })).json(); return (await (await request.post(`${teamUrl(session)}/accept${tokenQuery(result.invitationUrl)}`, { data: { name: email.split('@')[0] } })).json()); };

test('team invitations, role edits, confirmation, safe text, reset and last-owner controls work without network mutations', async ({ page }) => {
  const posts = []; page.on('request', request => { if (request.method() === 'POST') posts.push(request.url()); }); await page.goto(route);
  await expect(page.getByRole('combobox', { name: 'Role for Robin Francis', exact: true })).toBeDisabled(); await expect(page.getByRole('button', { name: 'Leave workspace as Robin Francis', exact: true })).toBeDisabled();
  const jamie = page.getByRole('combobox', { name: 'Role for Jamie Lee', exact: true }); await expect(page.getByRole('button', { name: 'Save role for Jamie Lee', exact: true })).toBeDisabled(); await jamie.selectOption('admin'); await page.getByRole('button', { name: 'Save role for Jamie Lee', exact: true }).press('Enter');
  await expect(page.getByRole('dialog')).toContainText('Set Admin access for Jamie Lee?'); await page.keyboard.press('Escape'); await expect(jamie).toHaveValue('admin');
  await page.getByRole('button', { name: 'Save role for Jamie Lee', exact: true }).click(); await confirm(page); await expect(page.getByRole('button', { name: 'Save role for Jamie Lee', exact: true })).toBeDisabled(); await expect(page.getByRole('searchbox', { name: 'Search team members' })).toBeFocused();
  await invite(page, 'avery@example.com'); const pending = root(page).locator('[data-rf-team-invitation]'); await expect(pending).toContainText('avery@example.com'); await expect(page.getByLabel('Invitation email', { exact: true })).toHaveValue('');
  await invite(page, 'AVERY@example.com'); await expect(root(page).locator('[data-rf-team-error]')).toContainText('already belongs'); await expect(pending).toHaveCount(1);
  await page.getByRole('button', { name: 'Clear invitation form', exact: true }).click(); await expect(page.getByRole('combobox', { name: 'Invitation role', exact: true })).toHaveValue('viewer');
  await pending.getByRole('combobox', { name: 'Role for avery@example.com', exact: true }).selectOption('editor'); await pending.getByRole('button', { name: 'Save invitation role for avery@example.com', exact: true }).click(); await confirm(page); await expect(pending.getByRole('combobox', { name: 'Role for avery@example.com', exact: true })).toHaveValue('editor');
  await pending.getByRole('button', { name: 'Revoke invitation for avery@example.com', exact: true }).click(); await confirm(page); await expect(pending).toHaveCount(0);
  await page.getByRole('searchbox', { name: 'Search team members' }).fill('nobody'); await expect(root(page).locator('[data-rf-team-empty]')).toBeVisible(); expect(posts).toEqual([]);
  await page.goto('/docs/index.html#component/team-invitation'); const malicious = '<img src=x onerror=window.teamXSS=1>'; await page.getByLabel('Your display name', { exact: true }).fill(malicious); await page.getByRole('button', { name: 'Join sample workspace' }).click(); await expect(page.locator('[data-rf-invite-status]')).toContainText(malicious); expect(await page.evaluate(() => window.teamXSS)).toBeUndefined();
  await page.locator('[data-rf-invite-accept-form]').evaluate(form => form.addEventListener('reset', event => event.preventDefault(), { once: true })); await page.getByRole('button', { name: 'Clear display name' }).click(); await expect(page.getByRole('button', { name: 'Join sample workspace' })).toBeDisabled(); await page.getByRole('button', { name: 'Clear display name' }).click(); await expect(page.getByRole('button', { name: 'Join sample workspace' })).toBeEnabled();
});

test('real local links rotate, accept once, expose current permissions and revoke access after leaving', async ({ page, request }) => {
  await page.goto('/dist/site/index.html#component/team-management'); await page.getByRole('button', { name: 'Start isolated local team' }).click(); await expect(root(page).locator('[data-rf-team-note]')).toContainText('Private local sample');
  await invite(page, 'local-viewer@example.com'); let link = await root(page).getByRole('link', { name: 'Open invitation', exact: true }).getAttribute('href'); const original = link;
  await page.getByRole('button', { name: 'Regenerate invitation for local-viewer@example.com', exact: true }).click(); await confirm(page); await expect(root(page).getByRole('link', { name: 'Open invitation', exact: true })).not.toHaveAttribute('href', original); link = await root(page).getByRole('link', { name: 'Open invitation', exact: true }).getAttribute('href');
  const id = new URL(link).searchParams.get('team'); expect((await request.get(`/api/sample-teams/${id}/invitation${tokenQuery(original)}`)).status()).toBe(410);
  const joined = await page.context().newPage(); await joined.goto(link); await expect(joined.getByLabel('Invited email', { exact: true })).toHaveValue('local-viewer@example.com'); await joined.getByLabel('Your display name', { exact: true }).fill('Avery Local'); await joined.getByRole('button', { name: 'Join sample workspace' }).click();
  await expect(joined.locator('[data-rf-invite-status]')).toContainText('invitation was consumed'); await expect(root(joined).locator('[data-rf-team-current-role]')).toHaveText('Viewer'); await expect(root(joined).getByRole('button', { name: 'Create invitation', exact: true })).toBeDisabled(); expect((await request.get(`/api/sample-teams/${id}/invitation${tokenQuery(link)}`)).status()).toBe(410);
  await page.getByRole('button', { name: 'Refresh team', exact: true }).click(); await expect(root(page).locator('[data-rf-team-count]')).toHaveText('4'); await expect(root(page).locator('[data-rf-team-invitation]')).toHaveCount(0);
  await root(joined).getByRole('button', { name: 'Leave workspace as Avery Local', exact: true }).click(); await confirm(joined); await expect(root(joined).locator('[data-rf-team-status]')).toContainText('membership ended'); await expect(root(joined).getByRole('button', { name: 'Refresh team', exact: true })).toBeDisabled(); await joined.close();
  await invite(page, 'stale@example.com'); await expect(root(page).locator('[data-rf-team-error]')).toContainText('Refresh'); await page.getByRole('button', { name: 'Refresh team', exact: true }).click(); await expect(root(page).locator('[data-rf-team-count]')).toHaveText('3');
  await page.getByRole('button', { name: 'Create invitation', exact: true }).click(); await page.getByRole('button', { name: 'Revoke invitation for stale@example.com', exact: true }).click(); await confirm(page); await expect(root(page).locator('[data-rf-team-invitation]')).toHaveCount(0);
});

test('HTTP role and scope checks reject privilege forgery, stale revisions, malformed bodies and cross-workspace tokens', async ({ request }) => {
  const owner = await create(request), other = await create(request), admin = await join(request, owner, 'admin@example.com', 'admin'), editor = await join(request, owner, 'editor2@example.com', 'editor'), viewer = await join(request, owner, 'viewer@example.com', 'viewer');
  expect((await request.get(teamUrl(owner))).status()).toBe(401); expect((await request.get(teamUrl(owner), { headers: auth(other) })).status()).toBe(401);
  for (const session of [editor, viewer]) expect((await change(request, session, { type: 'invite', email: 'forged@example.com', role: 'owner' })).status()).toBe(403);
  expect((await change(request, admin, { type: 'member-role', id: admin.actorId, role: 'owner' })).status()).toBe(403); expect((await change(request, admin, { type: 'remove', id: 'robin' })).status()).toBe(403); expect((await change(request, admin, { type: 'invite', email: 'boss@example.com', role: 'admin' })).status()).toBe(403);
  expect((await change(request, admin, { type: 'member-role', id: editor.actorId, role: 'viewer' })).status()).toBe(200);
  expect((await change(request, owner, { type: 'remove', id: 'robin' })).status()).toBe(409); expect((await change(request, owner, { type: 'member-role', id: 'robin', role: 'viewer' })).status()).toBe(409);
  expect((await change(request, owner, { type: 'invite', email: 'inject@example.com', role: 'viewer', actorId: 'robin' })).status()).toBe(400); expect((await change(request, owner, { type: 'invite', email: 'bad', role: 'viewer' })).status()).toBe(400); expect((await change(request, owner, { type: 'invite', email: 'ok@example.com', role: 'root' })).status()).toBe(400);
  expect((await change(request, owner, { type: 'invite', email: 'outdated@example.com', role: 'viewer' }, 0)).status()).toBe(409);
  expect((await request.post('/api/sample-teams', { headers: { Origin: 'https://untrusted.invalid' }, data: {} })).status()).toBe(403); expect((await request.post('/api/sample-teams', { data: { padding: 'x'.repeat(8192) } })).status()).toBe(413); expect((await request.post('/api/sample-teams', { headers: { 'Content-Type': 'text/plain' }, data: '{}' })).status()).toBe(415);
  expect((await change(request, owner, { type: 'remove', id: viewer.actorId })).status()).toBe(200); expect((await request.get(teamUrl(viewer), { headers: auth(viewer) })).status()).toBe(401);
  const pending = await (await change(request, owner, { type: 'invite', email: 'revoke@example.com', role: 'viewer' })).json(); const invitationId = pending.team.invitations.find(item => item.email === 'revoke@example.com').id; expect((await change(request, owner, { type: 'revoke', id: invitationId })).status()).toBe(200); expect((await request.post(`${teamUrl(owner)}/accept${tokenQuery(pending.invitationUrl)}`, { data: { name: 'Revoked' } })).status()).toBe(410);
  for (const session of [owner, other]) await request.delete(teamUrl(session), { headers: auth(session) });
});

test('concurrent demotions retain an owner; consumed links cannot mint two memberships and acceptance uses the latest role', async ({ request }) => {
  const owner = await create(request), second = await join(request, owner, 'owner2@example.com', 'owner'), revision = (await (await request.get(teamUrl(owner), { headers: auth(owner) })).json()).team.revision;
  const responses = await Promise.all([change(request, owner, { type: 'member-role', id: 'robin', role: 'editor' }, revision), change(request, second, { type: 'member-role', id: second.actorId, role: 'viewer' }, revision)]); expect(responses.map(response => response.status()).sort()).toEqual([200, 409]);
  const current = (await (await request.get(teamUrl(owner), { headers: auth(owner) })).json()).team; expect(current.members.filter(member => member.role === 'owner')).toHaveLength(1); const remaining = current.members.find(member => member.role === 'owner').id === 'robin' ? owner : second;
  expect((await change(request, remaining, { type: 'remove', id: remaining.actorId })).status()).toBe(409);
  const result = await (await change(request, remaining, { type: 'invite', email: 'once@example.com', role: 'editor' })).json(), invitationId = result.team.invitations.find(item => item.email === 'once@example.com').id;
  expect((await change(request, remaining, { type: 'invitation-role', id: invitationId, role: 'viewer' })).status()).toBe(200);
  const accepted = await Promise.all([request.post(`${teamUrl(owner)}/accept${tokenQuery(result.invitationUrl)}`, { data: { name: 'Once A' } }), request.post(`${teamUrl(owner)}/accept${tokenQuery(result.invitationUrl)}`, { data: { name: 'Once B' } })]); expect(accepted.map(response => response.status()).sort()).toEqual([201, 410]); const session = await accepted.find(response => response.status() === 201).json(); expect(session.team.members.find(member => member.id === session.actorId).role).toBe('viewer');
  await request.delete(teamUrl(remaining), { headers: auth(remaining) });
});

test('invalid snapshots and expired invitations fail; failed callbacks retain drafts, and teardown aborts and ignores late changes', async ({ page }) => {
  const team = { id: 'test', name: 'Test', revision: 0, members: [{ id: 'owner', name: 'Owner', email: 'owner@example.com', role: 'owner' }], invitations: [] };
  const pending = applyTeamChange(team, 'owner', { type: 'invite', email: 'expire@example.com', role: 'viewer' }, { now: 1000, lifetime: 1000, id: 'expire' }); expect(() => acceptTeamInvitation(pending, 'expire', 'Name', { now: 2000 })).toThrow(/expired/); expect(() => validateTeam({ ...team, invitations: [{ ...pending.invitations[0], expiresAt: 8640000000000001 }] })).toThrow(/Invalid invitation/);
  await page.goto(route); await page.evaluate(async () => { const { createTeamManager } = await import('/src/js/team-management.js'), { sampleTeam } = await import('/examples/team-demo.js'), element = document.querySelector('[data-rf-team-manager]'); createTeamManager(element).destroy(); window.teamManager = createTeamManager(element, { team: sampleTeam(), actorId: 'robin', change: async () => { throw Error('Save failed; try again.'); } }); });
  await page.getByRole('combobox', { name: 'Role for Jamie Lee', exact: true }).selectOption('admin'); await page.getByRole('button', { name: 'Save role for Jamie Lee', exact: true }).click(); await confirm(page); await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Save failed'); await page.keyboard.press('Escape'); await expect(page.getByRole('combobox', { name: 'Role for Jamie Lee', exact: true })).toHaveValue('admin');
  await page.evaluate(async () => { const { createTeamManager } = await import('/src/js/team-management.js'), { sampleTeam } = await import('/examples/team-demo.js'); window.teamManager.destroy(); window.teamManager = createTeamManager(document.querySelector('[data-rf-team-manager]'), { team: sampleTeam(), actorId: 'robin', change: (operation, context) => { window.teamSignal = context.signal; return new Promise(resolve => window.finishTeam = resolve); } }); });
  await invite(page, 'late@example.com'); await expect(root(page)).toHaveAttribute('aria-busy', 'true'); const outcome = await page.evaluate(async () => { const previous = window.teamManager.getTeam(); window.teamManager.destroy(); window.finishTeam({ team: { ...previous, revision: 1, invitations: [{ id: 'late', email: 'late@example.com', role: 'viewer', expiresAt: Date.now() + 10000 }] } }); await Promise.resolve(); await Promise.resolve(); return { aborted: window.teamSignal.aborted, revision: window.teamManager.getTeam().revision, rows: document.querySelectorAll('[data-rf-team-member]').length, invitations: document.querySelectorAll('[data-rf-team-invitation]').length, busy: document.querySelector('[data-rf-team-manager]').hasAttribute('aria-busy') }; }); expect(outcome).toEqual({ aborted: true, revision: 0, rows: 0, invitations: 0, busy: false });
});

test('dashboard reuses team management and isolates roles and invitations between workspaces', async ({ page }) => {
  await page.goto('/dist/site/examples/dashboard.html'); await invite(page, 'studio-only@example.com'); await page.getByRole('combobox', { name: 'Role for Jamie Lee', exact: true }).selectOption('admin'); await page.getByRole('button', { name: 'Save role for Jamie Lee', exact: true }).click(); await confirm(page);
  await page.locator('[data-dashboard-workspace-trigger]').click(); await page.getByRole('menuitem', { name: 'Personal workspace', exact: true }).click(); await expect(root(page).locator('[data-rf-team-count]')).toHaveText('1'); await expect(root(page).locator('[data-rf-team-invitation]')).toHaveCount(0); await invite(page, 'personal-only@example.com');
  await page.locator('[data-dashboard-workspace-trigger]').click(); await page.getByRole('menuitem', { name: 'Studio workspace', exact: true }).click(); await expect(root(page).locator('[data-rf-team-invitation]')).toHaveCount(1); await expect(root(page)).toContainText('studio-only@example.com'); await expect(page.getByRole('combobox', { name: 'Role for Jamie Lee', exact: true })).toHaveValue('admin'); await expect(root(page)).not.toContainText('personal-only@example.com');
  await page.getByRole('button', { name: 'Remove Alex Morgan', exact: true }).click(); await confirm(page); await expect(page.locator('[data-workspace-team] .rf-avatar')).toHaveCount(2); await expect(page.locator('[data-workspace-member-count="studio"]')).toHaveText('2');
  await page.reload(); await expect(root(page).locator('[data-rf-team-count]')).toHaveText('3'); await expect(root(page).locator('[data-rf-team-invitation]')).toHaveCount(0); await expect(page.getByRole('combobox', { name: 'Role for Jamie Lee', exact: true })).toHaveValue('editor');
});

test('team tables, errors, confirmation and invitation pages stay accessible at 320/390 pixels in both themes', async ({ page }) => {
  test.setTimeout(90000); await page.goto(route); await invite(page, 'a-long-collaborator-address-with-many-letters@example.com');
  for (const theme of ['light', 'dark']) { await page.evaluate(value => document.documentElement.dataset.rfTheme = value, theme); for (const width of [320, 390]) { await page.setViewportSize({ width, height: 844 }); expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width); } await page.evaluate(async () => { await Promise.all(document.getAnimations().filter(animation => animation.effect.getTiming().iterations !== Infinity).map(animation => animation.finished.catch(() => {}))); }); const result = await new AxeBuilder({ page }).include('.preview').withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze(); expect(result.violations).toEqual([]); await page.locator('.preview-shell').screenshot({ path: `output/playwright/rofin-team-${theme}-390.png` }); }
  await page.getByRole('button', { name: 'Revoke invitation for a-long-collaborator-address-with-many-letters@example.com', exact: true }).click(); const modal = await new AxeBuilder({ page }).include('dialog[open]').withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze(); expect(modal.violations).toEqual([]); await page.keyboard.press('Escape');
  await page.goto('/dist/site/examples/team-invite.html'); await expect(page.getByRole('button', { name: 'Join sample workspace' })).toBeDisabled(); await expect(page.locator('[data-rf-invite-error]')).toContainText('valid invitation'); expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
});
