import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('priorities commit once on drop or keyboard moves and reset to the initial order', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1200 });
  await page.goto('/docs/index.html#component/sortable-list');
  const list = page.locator('[data-rf-sort-list]');
  const order = () => list.locator('input[name="priority"]').evaluateAll(inputs => inputs.map(input => input.value));
  await page.evaluate(() => { window.moves = []; document.addEventListener('rf:sort-change', event => window.moves.push(event.detail)); });
  const down = page.getByRole('button', { name: 'Move Give the idea a shape. down', exact: true });
  await down.focus(); await page.keyboard.press('Enter');
  expect(await order()).toEqual(['prototype', 'brief', 'review', 'launch']);
  await expect(down).toBeFocused();
  expect(await page.evaluate(() => window.moves)).toEqual([{ value: 'brief', from: 0, to: 1, values: ['prototype','brief','review','launch'], previousValues: ['brief','prototype','review','launch'] }]);
  const up = page.getByRole('button', { name: 'Move Give the idea a shape. up', exact: true });
  await up.focus(); await up.press('Enter');
  await expect(down).toBeFocused();
  await list.locator('[data-rf-sort-item="brief"]').dragTo(list.locator('[data-rf-sort-item="launch"]'), { sourcePosition: { x: 20, y: 20 }, targetPosition: { x: 50, y: 75 } });
  expect(await order()).toEqual(['prototype','review','launch','brief']);
  expect(await page.evaluate(() => window.moves.length)).toBe(3);
  // Escape cancels a native drag without committing an intermediate arrangement.
  const source = await list.locator('[data-rf-sort-item="brief"]').boundingBox();
  const target = await list.locator('[data-rf-sort-item="prototype"]').boundingBox();
  await page.mouse.move(source.x + 30, source.y + 20); await page.mouse.down();
  await page.mouse.move(target.x + 30, target.y + 20, { steps: 12 }); await page.keyboard.press('Escape'); await page.mouse.up();
  expect(await order()).toEqual(['prototype','review','launch','brief']);
  expect(await page.evaluate(() => window.moves.length)).toBe(3);
  await page.getByRole('button', { name: 'Reset order' }).click();
  await expect(list.locator('input[name="priority"]').first()).toHaveValue('brief');
  expect(await order()).toEqual(['brief','prototype','review','launch']);
  await expect(page.getByRole('button', { name: 'Move Give the idea a shape. up', exact: true })).toBeDisabled();
  // Each initializer has its own drag state, so an external drop cannot reorder another list.
  await page.evaluate(async () => {
    const { initPatterns } = await import('/src/js/patterns.js');
    const host = document.createElement('div'); host.innerHTML = await (await fetch('/examples/components/sortable-list.html')).text(); document.body.append(host);
    let stop = initPatterns(host); const form = host.querySelector('form'), items = () => [...host.querySelectorAll('[data-rf-sort-item]')].map(item => item.dataset.rfSortItem);
    const button = host.querySelector('[data-rf-sort-move="1"]'); button.click();
    form.addEventListener('reset', event => event.preventDefault(), { once: true }); form.reset(); await new Promise(resolve => setTimeout(resolve, 10));
    if (items()[0] !== 'prototype') throw Error('Cancelled reset changed order');
    stop(); if (host.querySelector('[data-rf-sort-item]').hasAttribute('draggable') || !button.hidden || items()[0] !== 'prototype') throw Error('Teardown lost state or drag cleanup');
    let commits = 0; host.addEventListener('rf:sort-change', () => commits++); stop = initPatterns(host); button.click();
    if (commits !== 1) throw Error('Repeated initialization duplicated listeners');
    const target = host.querySelector('[data-rf-sort-item]'); target.dispatchEvent(new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer: new DataTransfer() }));
    if (commits !== 1) throw Error('External drop committed'); stop(); host.remove();
  });
});

test('task boards expose native moves, counts, empty columns, cancellation, reset, and cleanup', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1200 });
  await page.goto('/docs/index.html#component/kanban');
  const board = page.locator('[data-rf-kanban]');
  const draft = board.locator('[data-rf-kanban-column="Draft"]'), published = board.locator('[data-rf-kanban-column="Published"]');
  const move = page.getByRole('combobox', { name: 'Move to for Brand refresh', exact: true });
  await page.evaluate(() => { window.moves = []; document.addEventListener('rf:kanban-change', event => window.moves.push(event.detail)); });
  await move.selectOption('Published');
  await expect(move).toBeFocused();
  await expect(draft.locator('[data-rf-kanban-count]')).toHaveText('0');
  await expect(draft.locator('[data-rf-kanban-empty]')).toBeVisible();
  await expect(published.locator('[data-rf-kanban-count]')).toHaveText('2');
  expect(await page.evaluate(() => window.moves)).toEqual([{ value: 'project-3', from: 'Draft', to: 'Published' }]);
  await board.locator('[data-rf-kanban-item="project-3"]').dragTo(draft.locator('h3'), { sourcePosition: { x: 20, y: 20 } });
  await expect(move).toHaveValue('Draft');
  await expect(draft.locator('[data-rf-kanban-count]')).toHaveText('1');
  expect(await page.evaluate(() => window.moves.length)).toBe(2);
  await page.setViewportSize({ width: 320, height: 900 });
  await move.selectOption('In progress');
  await expect(board.locator('[data-rf-kanban-column="In progress"] [data-rf-kanban-item]')).toHaveCount(3);
  await page.getByRole('button', { name: 'Reset board' }).click();
  await expect(move).toHaveValue('Draft');
  await expect(board.locator('[role="status"]')).toHaveText('Original board restored.');
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  await page.evaluate(async () => {
    const { initPatterns } = await import('/src/js/patterns.js');
    const host = document.createElement('div'); host.innerHTML = await (await fetch('/examples/components/kanban.html')).text(); document.body.append(host);
    let stop = initPatterns(host), commits = 0; host.addEventListener('rf:kanban-change', () => commits++);
    const select = host.querySelector('[data-rf-kanban-item="project-3"] select'), change = value => { select.value = value; select.dispatchEvent(new Event('change', { bubbles: true })); };
    change('Published'); host.querySelector('form').addEventListener('reset', event => event.preventDefault(), { once: true }); host.querySelector('form').reset(); await new Promise(resolve => setTimeout(resolve, 10));
    if (select.value !== 'Published') throw Error('Cancelled reset changed board');
    stop(); if (select.closest('li').draggable || !select.closest('label').hidden || select.closest('[data-rf-kanban-column]').dataset.rfKanbanColumn !== 'Published') throw Error('Teardown lost committed move or cleanup');
    stop = initPatterns(host); change('Draft'); if (commits !== 2) throw Error('Repeated initialization duplicated listeners');
    const target = host.querySelector('[data-rf-kanban-column="Published"]'); target.dispatchEvent(new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer: new DataTransfer() }));
    if (commits !== 2) throw Error('External drop committed'); select.disabled = true; change('Published'); if (commits !== 2) throw Error('Disabled select moved card');
    stop(); host.remove();
  });
});

test('panel ratios and chart exploration follow native range controls and preserve exact data', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/docs/index.html#component/resizable-panels');
  const range = page.getByRole('slider', { name: 'First panel width', exact: true });
  await range.focus(); await page.keyboard.press('End');
  await expect(range).toHaveValue('75'); await expect(range).toHaveAttribute('aria-valuetext', '75% first panel, 25% second panel');
  const ratio = () => page.locator('.rf-resizable__panels').evaluate(element => element.children[0].getBoundingClientRect().width / element.children[1].getBoundingClientRect().width);
  expect(await ratio()).toBeCloseTo(3, 1);
  await page.setViewportSize({ width: 320, height: 900 });
  expect(await page.locator('.rf-resizable__panels').evaluate(element => element.children[1].getBoundingClientRect().top > element.children[0].getBoundingClientRect().bottom)).toBe(true);
  await expect(range).toHaveValue('75');
  await page.setViewportSize({ width: 1440, height: 1000 }); expect(await ratio()).toBeCloseTo(3, 1);
  await page.getByRole('textbox', { name: 'Your next step' }).fill('An unsaved thought');
  await page.getByRole('button', { name: 'Reset workspace' }).click();
  await expect(range).toHaveValue('40'); await expect(page.getByRole('textbox', { name: 'Your next step' })).toHaveValue('Prepare the first prototype for review.');
  await page.goto('/docs/index.html#component/line-chart');
  const month = page.getByRole('slider', { name: 'Chart month', exact: true }), readout = page.locator('[data-rf-line-readout]');
  await month.focus(); await page.keyboard.press('End');
  await expect(month).toHaveAttribute('aria-valuetext', 'September: Active members 72; Target 55');
  await expect(readout).toHaveText('September: Active members 72; Target 55');
  await expect(page.locator('polyline[data-rf-line-series="active"]')).toHaveAttribute('points', /528,20$/);
  const points = await page.locator('polyline[data-rf-line-series="target"]').getAttribute('points');
  await page.getByRole('checkbox', { name: 'Active members · solid', exact: true }).uncheck();
  await expect(page.locator('polyline[data-rf-line-series="active"]')).toBeHidden();
  await expect(readout).toHaveText('September: Target 55');
  await expect(page.locator('polyline[data-rf-line-series="target"]')).toHaveAttribute('points', points);
  await page.getByRole('checkbox', { name: 'Target · dashed', exact: true }).uncheck();
  await expect(month).toHaveAttribute('aria-valuetext', 'September: No series selected.');
  await page.getByText('View line chart data', { exact: true }).click();
  expect(await page.getByRole('table', { name: 'Active members and targets, April–September' }).locator('tbody td:first-of-type').allTextContents()).toEqual(['24','38','31','52','48','72']);
  await page.goto('/dist/site/index.html#component/line-chart');
  const downloaded = page.waitForEvent('download');
  await page.getByRole('link', { name: 'examples/components/line-chart.html', exact: true }).click();
  const download = await downloaded; expect(download.suggestedFilename()).toBe('line-chart.html');
  expect(await readFile(await download.path(), 'utf8')).toContain('data-rf-line-chart');
  await page.goto('/docs/index.html#component/line-chart');
  await page.evaluate(async () => {
    const { initPatterns } = await import('/src/js/patterns.js');
    const host = document.createElement('form'); host.innerHTML = await (await fetch('/examples/components/line-chart.html')).text(); document.body.append(host);
    const stop = initPatterns(host), range = host.querySelector('[data-rf-line-range]'); range.value = '5'; range.dispatchEvent(new Event('input'));
    host.querySelector('[data-rf-line-toggle]').checked = false; host.querySelector('[data-rf-line-toggle]').dispatchEvent(new Event('change'));
    host.reset(); await new Promise(resolve => setTimeout(resolve, 10));
    if (!range.getAttribute('aria-valuetext').includes('April: Active members 24; Target 30')) throw Error('Chart reset lost default month/series');
    stop(); if (!host.querySelector('[data-rf-line-controls]').hidden || range.hasAttribute('aria-valuetext')) throw Error('Chart teardown lost fallback');
    host.querySelector('tbody td').textContent = 'unknown'; const cleanup = initPatterns(host);
    if (!host.querySelector('[data-rf-line-controls]').hidden) throw Error('Non-numeric chart data was enhanced'); cleanup(); host.remove();
  });
});

test('the composed board shares table state across moves, filters, creation, and archiving', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/dist/site/examples/dashboard.html');
  const board = page.locator('#project-board');
  await expect(board.locator('[data-rf-kanban-item]')).toHaveCount(6);
  await board.locator('[data-rf-kanban-item="project-3"]').dragTo(board.locator('[data-rf-kanban-column="Published"] h3'));
  await expect(page.locator('#projects tr:has(input[value="project-3"])')).toHaveAttribute('data-rf-status', 'Published');
  const move = board.getByRole('combobox', { name: 'Move to for Brand refresh', exact: true }); await expect(move).toBeFocused();
  await page.getByRole('combobox', { name: 'Project status', exact: true }).selectOption('Published');
  await expect(page.locator('#filter-status')).toContainText('of 3 rows');
  await move.selectOption('Draft'); await expect(move).toBeFocused();
  await expect(page.locator('#filter-status')).toContainText('of 2 rows');
  await expect(board.locator('[data-rf-kanban-item]')).toHaveCount(6);
  await page.getByRole('button', { name: 'New project +', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Make room for a new idea.' });
  await dialog.getByRole('textbox', { name: 'Project name' }).fill('<next & better>');
  await dialog.getByRole('button', { name: 'Create project', exact: true }).click();
  await expect(board.locator('[data-rf-kanban-item]')).toHaveCount(7);
  await expect(board.locator('[data-rf-kanban-item="project-7"] [data-rf-item-label]')).toHaveText('<next & better>');
  await board.getByRole('combobox', { name: 'Move to for <next & better>', exact: true }).selectOption('In progress');
  await expect(page.locator('#projects tr:has(input[value="project-7"])')).toHaveAttribute('data-rf-status', 'In progress');
  await page.getByRole('checkbox', { name: 'Select <next & better>', exact: true }).check();
  await page.getByRole('button', { name: 'Archive selected', exact: true }).click();
  await page.getByRole('dialog', { name: 'Archive selected projects?' }).getByRole('button', { name: 'Archive projects', exact: true }).click();
  await expect(board.locator('[data-rf-kanban-item]')).toHaveCount(6);
  await expect(board.locator('[data-rf-kanban-item="project-7"]')).toHaveCount(0);
  await board.getByRole('combobox', { name: 'Move to for Component library', exact: true }).selectOption('Published');
  await expect(page.locator('#projects tr:has(input[value="project-4"])')).toHaveAttribute('data-rf-status', 'Published');
  for (const theme of ['light','dark']) {
    await page.locator('html').evaluate((element, theme) => { element.dataset.rfTheme = theme; }, theme);
    await page.setViewportSize({ width: 1440, height: 1000 }); await board.screenshot({ path: `output/playwright/rofin-project-board-${theme}.png` });
    await page.setViewportSize({ width: 320, height: 900 });
    await board.getByRole('combobox', { name: 'Move to for Brand refresh', exact: true }).selectOption('In progress');
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  }
  expect(errors).toEqual([]);
});
